[workspace]
members = [
  "core",
  "dsl",
  "types",
  "cli",
  "runtime",
  "verification",
  "protocols",
  "templates"
]

[patch.crates-io]
sv = { git = "https://github.com/murphsicles/rust-sv", tag = "v0.4.1" }
