[package]
name = "nprint-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
nprint-types = { path = "../types" }    # Shared types for contracts
nprint-core = { path = "../core" }     # Core Bitcoin Script logic
sv = { git = "https://github.com/murphsicles/rust-sv", tag = "v0.4.1" }  # Bitcoin Script opcodes
nprint-protocols = { path = "../protocols" }
nprint-templates = { path = "../templates" }
nprint-dsl = { path = "../dsl" }
tokio = { version = "1.38.0", features = ["full"] }  # Async
reqwest = { version = "0.12.5", features = ["json"] }  # RPC calls
thiserror = "1.0.61"  # Errors

[features]
default = []
