[package]
name = "nprint-types"
version = "0.1.0"
edition = "2021"

[dependencies]
nprint-core = { path = "../core" }
serde = { version = "1.0", features = ["derive"] }
sv = { git = "https://github.com/murphsicles/rust-sv", tag = "v0.4.1" }

[features]
default = []
