[package]
name = "nprint-templates"
version = "0.1.0"
edition = "2021"

[dependencies]
nprint-types = { path = "../types" }    # Shared types for contracts
nprint-core = { path = "../core" }     # Core Bitcoin Script logic
sv = { git = "https://github.com/murphsicles/rust-sv", tag = "v0.4.1" }  # Bitcoin Script opcodes
nprint-dsl = { path = "../dsl" }       # DSL for contract templates
serde = { version = "1.0.204", features = ["derive"] }  # For serialization

[features]
default = []
