[package]
name = "nprint-templates"
version = "0.1.0"
edition = "2021"

[dependencies]
nprint-core = { path = "../core" }
nprint-dsl = { path = "../dsl" }
nprint-types = { path = "../types" }
serde = { version = "1.0", features = ["derive"] }

[features]
default = []
std = []
