name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - name: Clear Cargo cache
      run: rm -rf ~/.cargo/git ~/.cargo/registry
    - name: Update dependencies
      run: cargo update
    - name: Build
      run: cargo build --workspace --verbose
    - name: Run tests
      run: cargo test --workspace --verbose
    - name: Clippy
      run: cargo clippy --workspace -- -D warnings
    - name: Fmt
      run: cargo fmt --all -- --check
    - name: Bench
      run: cargo bench --workspace || echo "Benchmarks not implemented, skipping"
