name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Publish crates
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        cargo publish -p nprint-types
        cargo publish -p nprint-core
        cargo publish -p nprint-dsl
        cargo publish -p nprint-templates
        cargo publish -p nprint-protocols
        cargo publish -p nprint-runtime
        cargo publish -p nprint-verification
        cargo publish -p nprint-cli
